name: Create CloudFormation Stack

on:
  pull_request:

jobs:
  create_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired AWS region

      #- name: Create CloudFormation Stack
      #  run: |
      #    aws cloudformation create-stack --stack-name myteststack --template-body file://ec2.yaml

      - name: Check endpoint availability
        run: |
          set -e
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" \
            --connect-timeout 5 --max-time 10 \
            --retry 2 --retry-delay 3 \
            http://44.204.72.182 || echo "000")

          if [[ "$HTTP_STATUS" -ne 200 ]]; then
            echo "Smoke test failed! HTTP status: $HTTP_STATUS"
            exit 1
          fi
          echo "Smoke test passed! HTTP status: $HTTP_STATUS"

      - name: Check endpoint availability
        run: |
          set -e
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" \
            --connect-timeout 5 --max-time 10 \
            --retry 2 --retry-delay 3 \
            http://44.204.72.181 || echo "000")

          if [[ "$HTTP_STATUS" -ne 200 ]]; then
            echo "Smoke test failed! HTTP status: $HTTP_STATUS"
            exit 1
          fi
          echo "Smoke test passed! HTTP status: $HTTP_STATUS"